### ISSUE TITLE
Use case with Chrome extensions

### ISSUE THREAD

**Issue by shanemcgraw** [OnetapInc/chromy#51]
I have a Chrome extension that I was hoping to use Chromy to load and test. However, since Chromy loads a fresh copy of Chrome on startup (no one signed in, etc.), this appears to be impossible. 

Would it be possible to load an extension inside whichever instance Chromy runs?

**Comment by dotneet** [comment]
Hi @shanemcgraw,

I've published new version to support loading extensions now!
Please try it out!

Here is an example.

```js
const Chromy = require('chromy')

const chromy = new Chromy({
  visible: true,
  userDataDir: "/Users/YourName/Library/Application Support/Google/Chrome/",
  enableExtensions: true
})

chromy.chain().goto('https://example.com').end()
```

The new option `enableExtensions` enable loading extensions.
Generally this option should be used with `userDataDir` option because extensions are installed in userDataDir.

**Comment by garris** [comment]
@dotneet   FANTASTIC!  I will add this to Backstop ASAP.

**Comment by shanemcgraw** [comment]
Thank you @dotneet!!

**Comment by seleckis** [comment]
I'm trying to make it work, but unfortunately Flash extension in my Chrome is not running. Has something changed since this issue was resolved?

This config:
```js
let chromy = new Chromy({
  visible:true,
  enableExtensions: true,
  launchBrowser: false,
  userDataDir: '/Users/seleckis/Library/Application Support/Google/Chrome/'
});
```
Opens Chrome, but flash extension is not running:
<img width="719" alt="screen shot 2018-09-21 at 10 01 02" src="https://user-images.githubusercontent.com/988504/45867847-0400cd80-bd8d-11e8-9149-c6bad3cb340a.png">
